### PR TITLE
add text scaling

### PR DESCRIPTION
**Pull request by TG-Techie**

### CODE REVIEW

**Comment by ladyada** [comment]
_text and text should be combined, have size be a kwarg

**Comment by TG-Techie** [comment]
pushed

**Comment by dherrada** [comment]
I'll fork your repo and see if I can try to get this fixed.

**Comment by dherrada** [comment]
@kattni I'm 99.9% sure this is an issue with Travis. I've tried literally everything in #17. I even changed the docstring to one line with nothing that would possibly make Travis upset. Other than that, I can't find any issues with the code.

**Comment by siddacious** [comment]
It certainly looks like an issue with the docs building because of a docstring, though it might have been caused by something earlier in the file. @TG-Techie or @dherrada did either or both of you build the docs locally? If so, did you get the same error?

**Comment by dherrada** [comment]
@siddacious I tried building it locally but it didn’t give me any issues.

**Comment by dherrada** [comment]
Moving to #23

**Pull request closed without merging**
